version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: development
      redis_server: redis
      redis_port: 8001
    depends_on:
      - redis
  redis:
    image: "redis:alpine"