version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: production
      FLASK_APP: __init__.py
      FLASK_RUN_PORT: 8000
      redis_server: redis
      redis_port: 8001
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - ./redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    ports:
      - "8001:8001"
