FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev build-essential
COPY . /app
WORKDIR /app


ENV FLASK_APP app
ENV FLASK_ENV DEVELOPMENT
ENV FLASK_RUN_PORT 8000
ENV SECRET_KEY KEYSLOVEMONKEY

RUN pip3 install -r requirements.txt

RUN python3 -m flask run
