FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev build-essential
COPY . /app
WORKDIR /app
CMD ["virtualenv venv"]
CMD ["source venv/bin/activate"]
RUN pip3 install -r requirements.txt

CMD ["flask run"]